// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';

import { RemoteEntryComponent } from './entry.component';

export const routes: Routes = [
  {
    path: '',
    redirectTo: 'first-microfrontend',
    pathMatch: 'full',
  },
  {
    path: 'first-microfrontend',
    component: RemoteEntryComponent,
    children: [],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class RemoteEntryRouterModule {}
