// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';

import { RemoteEntryComponent } from './remote-entry.component';

import { RemoteEntryChildComponent } from './remote-entry.component';

export const routes: Routes = [
  {
    path: '',
    component: RemoteEntryComponent,
    children: [],
  },
  {
    path: 'child',
    component: RemoteEntryChildComponent,
    children: [],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class RemoteEntryRouterModule {}
