// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home/home.component';

import { PageNotFoundComponent } from './page-not-found/page-not-found.component';
import { WebComponentWrapper, WebComponentWrapperOptions } from '@modulefederation/components';

export const localRoutes: Routes = [
  {
    path: '',
    redirectTo: 'home',
    pathMatch: 'full',
  },
  {
    path: 'home',
    component: HomeComponent,
    children: [],
  },
    { // TODO react
       path: 'react',
       component: WebComponentWrapper,
       data: {
           remoteEntry: 'http://localhost:4205/remoteEntry.js', // ?
           remoteName: 'react-remote',
           exposedModule: './Module',
           elementName: 'react-element'
       } as WebComponentWrapperOptions
    },

  {
    path: '**',
    component: PageNotFoundComponent,
  },
];
