keycloak:
  realm: service
  auth-server-url: = http://127.0.0.1:8080/auth
  ssl-required: external
  resource: service-browser
  use-resource-role-mappings: true
  bearer-only: true
spring:
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/service
          jwk-set-uri: http://localhost:8080/realms/service/protocol/openid-connect/certs
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path:}/actuator/health
        health-check-interval: 15s
        health-check-timeout: 90s
        health-check-critical-timeout: 3m
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
