logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
  level:
    root: INFO
  file:
    name: "log/hello.log"
server:
  port: 8083
service:
  package: com.serious
web:
  cors:
    allowed-origins: "http://localhost:*"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
spring:
  application:
    name: demo
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
