// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes } from '@angular/router';

import { MirofrontendsComponent } from './portal/microfrontends.component';

import { MicrofrontendDetailsComponent } from './portal/microfrontend-details.component';

import { NodesComponent } from './nodes/nodes.component';

import { HomeComponent } from './home/home-component';

import { ComponentsComponent } from './components/components.component';

import { ComponentDetailsComponent } from './components/component-details.component';

import { ServiceInstanceComponent } from './components/service-instance.component';

export const localRoutes : Routes = [
    {
        path: '',
        redirectTo: 'microfrontends',
        pathMatch: 'full',
    },
    {
        path: 'microfrontends',
        component: MirofrontendsComponent,
        children: [
            {
                path: ':microfrontend',
                component: MicrofrontendDetailsComponent,
                children: [],
            },
        ],
    },
    {
        path: 'nodes',
        component: NodesComponent,
        children: [],
    },
    {
        path: 'home',
        component: HomeComponent,
        children: [],
    },
    {
        path: 'components',
        component: ComponentsComponent,
        children: [
            {
                path: ':component',
                component: ComponentDetailsComponent,
                children: [
                    {
                        path: ':instance',
                        component: ServiceInstanceComponent,
                        children: [],
                    },
                ],
            },
        ],
    },
];
