// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';
import { PortalManager } from '@modulefederation/portal';

import { PublicPortalComponent } from './public-portal-component';

export const routes: Routes = [
  {
    path: '',
    component: PublicPortalComponent,
    children: [],
  },
];

@NgModule({
  imports: [
    RouterModule.forChild(
      PortalManager.registerLazyRoutes('<%= name %>.public-portal', routes)
    ),
  ],

  exports: [RouterModule],
})
export class PublicPortalRouterModule {}
