// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import {Routes} from '@angular/router';

import {HomeComponent} from './home/components/home/home.component';

export const localRoutes : Routes = [
    {
        path: '',
        redirectTo: 'home',
        pathMatch: 'full',
    },
    {
        path: 'home',
        component: HomeComponent,
        children: [],
    },
];
