// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';
import { localRoutes } from './local.routes';


@NgModule({
  imports: [
    RouterModule.forRoot(localRoutes)
  ],

  exports: [RouterModule],
})
export class ShellRouterModule {
}
