// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';
import { PortalManager } from '@modulefederation/portal';

import { PrivatePortalComponent } from './private-portal-component';

export const routes: Routes = [
  {
    path: '',
    component: PrivatePortalComponent
  },
];

@NgModule({
  imports: [
    RouterModule.forChild(
      PortalManager.registerLazyRoutes('<%= name %>.private-portal', routes)
    ),
  ],

  exports: [RouterModule],
})
export class PrivatePortalRouterModule {}
