// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';
import { PortalManager } from '@modulefederation/portal';

import { LazyComponent } from './lazy-child.component';

export const routes: Routes = [
  {
    path: '',
    component: LazyComponent,
    children: [],
  },
];

@NgModule({
  imports: [
    RouterModule.forChild(
      PortalManager.registerLazyRoutes(
        'first-microfront.private-portal.lazy-child',
        routes
      )
    ),
  ],

  exports: [RouterModule],
})
export class LazyChildRouterModule {}
