// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';
import { PortalManager } from '@modulefederation/portal';

import { RemoteEntryChildComponent } from './child-component';

export const routes: Routes = [
  {
    path: '',
    component: RemoteEntryChildComponent,
    children: [],
  },
];

@NgModule({
  imports: [
    RouterModule.forChild(
      PortalManager.registerLazyRoutes('first-microfront.child', routes)
    ),
  ],

  exports: [RouterModule],
})
export class RemoteEntryChildRouterModule {}
