// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';

import { RemoteEntryChildComponent } from './child-component';
import {PortalConfigurationService} from "@modulefederation/portal";

export const routes: Routes = [
  {
    path: '',
    component: RemoteEntryChildComponent,
    children: [],
  },
];

@NgModule({
  imports: [RouterModule.forChild(PortalConfigurationService.registerLazyRoutes("first-microfront.child", routes))],
  exports: [RouterModule],
})
export class RemoteEntryChildRouterModule {}
